#!/bin/bash

mysql -u root -p"$MYSQL_ROOT_PASSWORD" -h ${MYSQL_HOST} -e "CREATE DATABASE IF NOT EXISTS $MYSQL_DATABASE; GRANT ALL ON $MYSQL_DATABASE.* TO $MYSQL_USER;"
mysql -u root -p"$MYSQL_ROOT_PASSWORD" -h ${MYSQL_HOST} -e "CREATE DATABASE IF NOT EXISTS $MYSQL_TEST_DATABASE; GRANT ALL ON $MYSQL_TEST_DATABASE.* TO $MYSQL_USER;"
